version: '3.8'

services:
  fastapi:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis-11101.c325.us-east-1-4.ec2.redns.redis-cloud.com
      - POSTGRES_URL=postgresql://postgres:password@postgres/dbname
      - USDA_API_KEY=WOoxO6VLGdMm2Jhb4BjecffIcv2FdQ52BsNOc2BS
      - REDIS_PORT=11101
      - REDIS_PASSWORD=otFl5i1OjgXaBl7DvhDgtfPhtu6jVgXo
      - JWT_SECRET_KEY="LWO9U6PgpmsHHVK0z8gY0-Dk2ZQf0_ya-gIJ6_y4wAs"
      - DATABASE_URL=postgresql://postgres:password@postgres/dbname


  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app_network
    expose:
      - "6379"  # Exposes Redis port internally to other containers
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - app_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
