version: '3.8'

services:
  fastapi:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/dbname

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app_network
    expose:
      - "6379"  # Exposes Redis port internally to other containers
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - app_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
